### ISSUE TITLE
IE8 and browserclass

### ISSUE THREAD

**Issue by veke** [hosszukalman/browserclass#2]
If you comment the window.load event from the bottom of the browserclass file and use browserclass with jquerys document ready, IE8 says Object doesn't support this property or method on line 212, character 7.

$(function() {

```
BrowserClass.init();
// do something with the classes 
// example $('body').addClass(BrowserClass.classes.join(' '));   
```

}

**Comment by hosszukalman** [comment]
IE8 is not supported in jQuery 2.x. Maybe this is the problem. Could you try with jQuery 1.x? If the problem exists, I will check the implementation in IE8

**Comment by veke** [comment]
BrowserClass has no jQuery requirement. Anyway, I used with 1.x jQuery. I think this is not jQuery problem.

**Comment by hosszukalman** [comment]
I know BrowserClass requirements but thanks for the note :) . Can you reproduce the problem if you don't comment the plugin's source?

**Comment by veke** [comment]
I know you know :) I was just wondering at loud. I was confused what jquery has anything to do with this. :) Let's see if I can reproduce the problem, or was it something with my setup.

**Comment by hosszukalman** [comment]
OK, thanks and please let me know what  is the result of your test!

**Comment by veke** [comment]
The IE8 error was not jquery and document ready problem. It is the script. I'm will not study the code, just inform you :D

http://jsbin.com/mohelebemofu/1

If you view this with IE8 you get error on line 233 char 7
